services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-backend
    image: django-backend
    user: django-user
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - django_static:/app/static
      - django_media:/app/media
    env_file: .env
    command: >
      sh -c "python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:14.6-alpine
    container_name: postgres-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer-postgres
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

volumes:
  postgres_data:
    driver: local
  django_static:
    driver: local
  django_media:
    driver: local

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1452
